django_study/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path("admin/", admin.site.urls),
    # pybo/ 로 시작되는 페이지 요청은 모두 pybo/urls.py 파일에 있는 URL 매핑을 참고하여 처리함함
    path('pybo/', include('pybo.urls')), 
]

django_study/mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detal'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

django_study/mysite/pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    # Question 모델 데이저 조회 결과에 속성값 보여 주기
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

"""
>>> python manage.py shell

in [1]: from pybo.models import Question, Answer

in [2]: from django.utils import timezone

in [3]: q = Question(
                subject='pybo가 무엇인가요?',
                content='pybo에 대해서 알고 싶습니다.',
                create_date=timezone.now())

in [4]: q.save()

>>> q.id
1

>>> q = Question(
            subject='장고 모델 질문입니다.',
            content='id는 자동으로 생성되나요?',
            create_date=timezone.now())

>>> q.save()
>>> q.id
2

>>> Question.objects.all()
<QuerySet [<Question: Question object (1)>, <Question: Question object (2)>]>
"""

django_study/mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

django_study/mysite/pybo/views.py
from django.http import HttpResponse
# 모델 데이터를 템플릿 파일을 사용해 화면에 출력함-> render
from django.shortcuts import render, get_object_or_404
from .models import Question

# Create your views here.
def index(request):
    """pybo 목록 출력"""

    # Question 모델 데이터 작성일시 역순으로 조회하기(-create_date)
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    
    # render로 화면 출력하기기
    return render(request, 'pybo/question_list.html', context)
    # return HttpResponse("안녕하세요 pybo에 오신 것을 환영합니다.")

""" *render()

context에 있는 Question 모델 데이터 question_list를 pybo/question_list.html 파일에 적용해 
HTML 코드로 변환함.
장고에서는 이런 파일(pybo/question_list.html)을 템플릿이라 부름.
장고의 태그를 추가로 사용할 수 있는 HTML 파일이라고 생각하면 됨.
"""

def detail(request, question_id):
    """pybo 내용 출력"""
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
)
from .models import Question
from django.utils import timezone
from .forms import QuestionForm, AnswerForm


def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == 'POST':
        form = AnswerForm(request.POST)

        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()

            return redirect(
                'pybo:detail', question_id=question_id
            )
    else:
        form = AnswerForm()
    context = {
        'question': question,
        'form': form,
    }
    return render(
        request, 'pybo/question_detail.html', context
    )


def question_create(request):
    """
    pybo 질문 등록
    """

    # form = QuestionForm()
    # return render(
    #     request,
    #     'pybo/question_form.html',
    #     {'form': form},
    # )

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(
        request, 'pybo/question_form.html',
        context,
    )

django_study/mysite/templates/pybo/base.html
{% load static %}
<!doctpye html>
<html lang="ko">
<head>
    <!--Requried meta tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!--pybo CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 내비게이션바 -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">로그인</a>
            </li>
        </ul>
    </div>
 </nav>
<!--기본 템플릿 안에 삽입될 내용 Start-->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 End-->
</body>
</html>

django_study/mysite/templates/pybo/question_detail.html
<!-- <h1>{{ question.subject }}</h1>

<div>
    {{ question.content }}
</div>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"> -->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-text" style="white-space: pre-line;">
            {{ answer.content }}
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2">
                {{ answer.create_date }}
            </div>
        </div>
    </div>
</div>
{% endfor %}
<form action="{% url 'pybo:answer_create' question.id %}"
    method="post" class="my-3">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {{% endif %}}
    {% endfor %}
    </div>
    <div class="form-group">
        <textarea name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변 등록" class="btn btn-primary">
</form>
{% endblock %}

django_study/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {%csrf_token %}
        <!-- 오류 표시 Start -->
         {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
    <!-- 오류 표시 End -->
    <div class="form-group">
        <label for="subject">제목</label>
        <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_done_none:'' }}">
    </div>
    <div class="form-group">
        <label for="content">내용</label>
        <textarea class="form-control" name="content" id="content"
                    rows="10">{{ form.content.value|default_if_done_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

django_study/mysite/templates/pybo/question_list.html
<!-- {% if question_list %}   
    <ul>
    {% for question in question_list %}
        <li><a href="/pybo/{{ question.id }}/">{{ question.subject }}</a></li>
        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
    {% endfor %}    
    </ul>
{% else %}  
    <p>질문이 없습니다.</p>
{% endif %}

{% load static %} -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"> -->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
        질문 등록하기
    </a>
</div>
{% endblock %}